Header header
string file_name
string file_name_1
string file_name_2
string dmp_name
geometry_msgs/Pose[] poses_r
geometry_msgs/Pose[] poses_l
float64[] initial_pose
float64[] goal_pose
geometry_msgs/Pose[] weights
int64 n_bfs
int64 n_dmps
float64 tau
float64 dt
int32 time_step

---
string result
geometry_msgs/Pose[] poses_r
float64[] g_value